<?php
 	$_SESSION = array();
 	header("Location:index.php?p=login");
 	print "Vous êtes déconnecté"
 ?>
<p><a href="index.php?p=login"> Se connecter </a></p>


erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyf tdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu
erizfodkjfhksfhbjsdxrcfthbjnk,olkijugyftcrdxcrftvbhyjnuiko
olkijuhgyftrdtfklpmkojihugyftdrijkolpkojihugyftdrtfyguhjhu